import React, { useState } from "react";
import { Monitor } from "../App";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { FileText, DollarSign, Calculator, Loader2, CheckCircle2, Download, Plus } from "lucide-react";
import { quantifyDamages } from "../lib/gemini";
import { motion } from "motion/react";
import { Badge } from "@/components/ui/badge";
import { jsPDF } from "jspdf";
import { toast } from "sonner";
import { format } from "date-fns";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog";

interface InsuranceClaimsProps {
  monitors: Monitor[];
}

export default function InsuranceClaims({ monitors }: InsuranceClaimsProps) {
  const [downtime, setDowntime] = useState("");
  const [context, setContext] = useState("E-commerce checkout API for high-traffic retail site. Average transaction value $85.");
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isManualDialogOpen, setIsManualDialogOpen] = useState(false);
  const [manualClaim, setManualClaim] = useState({
    service: "",
    amount: "",
    justification: ""
  });

  const handleQuantify = async () => {
    if (!downtime) return;
    setLoading(true);
    try {
      const data = await quantifyDamages(parseInt(downtime), context);
      setResult(data);
    } catch (error) {
      console.error("Quantification failed", error);
    } finally {
      setLoading(false);
    }
  };

  const handleGeneratePDF = async (customData?: any) => {
    const data = customData || result;
    if (!data) return;
    setIsGenerating(true);
    
    try {
      const doc = new jsPDF();
      const timestamp = data.timestamp || format(new Date(), "yyyy-MM-dd HH:mm:ss");
      const claimId = data.id || (result === data ? `CLM-${Math.floor(Math.random() * 90000) + 10000}` : data.id);
      const amount = data.estimatedLoss || data.amount;
      const justification = data.claimJustification || data.justification || "Automated claim justification based on service interruption and business impact analysis.";
      const breakdown = data.breakdown || {
        directLoss: amount * 0.6,
        indirectLoss: amount * 0.3,
        reputationDamage: amount * 0.1
      };

      // Header
      doc.setFillColor(20, 20, 20);
      doc.rect(0, 0, 210, 40, 'F');
      
      doc.setTextColor(228, 227, 224);
      doc.setFontSize(24);
      doc.setFont("helvetica", "bold");
      doc.text("INSUREAPI", 20, 25);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("OFFICIAL DAMAGE ASSESSMENT & CLAIM REPORT", 20, 32);

      // Claim Info
      doc.setTextColor(20, 20, 20);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("CLAIM INFORMATION", 20, 55);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Claim ID: ${claimId}`, 20, 65);
      doc.text(`Generated At: ${timestamp}`, 20, 72);
      if (downtime && data === result) {
        doc.text(`Downtime Duration: ${downtime} Minutes`, 20, 79);
      }

      // Financials
      doc.setFont("helvetica", "bold");
      doc.text("FINANCIAL QUANTIFICATION", 20, 95);
      
      doc.setFont("helvetica", "normal");
      doc.text(`Estimated Total Loss: $${amount.toLocaleString()}`, 20, 105);
      doc.text(`- Direct Loss: $${breakdown.directLoss.toLocaleString()}`, 30, 112);
      doc.text(`- Indirect Loss: $${breakdown.indirectLoss.toLocaleString()}`, 30, 119);
      doc.text(`- Reputation Damage: $${breakdown.reputationDamage.toLocaleString()}`, 30, 126);

      // Justification
      doc.setFont("helvetica", "bold");
      doc.text("CLAIM JUSTIFICATION", 20, 145);
      
      doc.setFont("helvetica", "italic");
      const splitText = doc.splitTextToSize(justification, 170);
      doc.text(splitText, 20, 155);

      // Footer
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("This document is an automated assessment generated by the InsureAPI Neural Engine.", 20, 280);
      doc.text("Verification required by a certified claims adjuster.", 20, 285);

      doc.save(`InsureAPI_Claim_${claimId}.pdf`);
      toast.success("Official Claim PDF Generated", {
        description: `File: InsureAPI_Claim_${claimId}.pdf`
      });
    } catch (error) {
      console.error("PDF generation failed", error);
      toast.error("Failed to generate PDF");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleManualSubmit = () => {
    if (!manualClaim.service || !manualClaim.amount) {
      toast.error("Please fill in all required fields");
      return;
    }
    
    const claimId = `CLM-${Math.floor(Math.random() * 90000) + 10000}`;
    handleGeneratePDF({
      id: claimId,
      amount: parseFloat(manualClaim.amount),
      justification: manualClaim.justification,
      timestamp: format(new Date(), "yyyy-MM-dd HH:mm:ss")
    });
    setIsManualDialogOpen(false);
    setManualClaim({ service: "", amount: "", justification: "" });
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4 mb-8">
        <div className="w-12 h-12 bg-[#141414] flex items-center justify-center">
          <DollarSign className="text-[#E4E3E0] w-8 h-8" />
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tighter uppercase">Claims & Damage Assessment</h2>
          <p className="text-xs opacity-60 uppercase tracking-widest">Financial Loss Quantification Engine</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="border-[#141414] rounded-none shadow-none bg-transparent">
          <CardHeader className="border-b border-[#141414] py-4">
            <CardTitle className="text-xs uppercase tracking-widest flex items-center gap-2">
              <Calculator className="w-4 h-4" /> Damage Calculator
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6 space-y-6">
            <div className="space-y-2">
              <Label className="text-[10px] uppercase tracking-widest font-bold">Downtime Duration (Minutes)</Label>
              <Input 
                type="number" 
                placeholder="e.g. 45" 
                value={downtime}
                onChange={(e) => setDowntime(e.target.value)}
                className="rounded-none border-[#141414] bg-transparent font-mono"
              />
            </div>
            <div className="space-y-2">
              <Label className="text-[10px] uppercase tracking-widest font-bold">Business Context & Impact</Label>
              <textarea 
                className="w-full min-h-[100px] p-3 rounded-none border border-[#141414] bg-transparent font-mono text-xs resize-none focus:outline-none"
                placeholder="Describe what this API does and the impact of its failure..."
                value={context}
                onChange={(e) => setContext(e.target.value)}
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Button 
                onClick={handleQuantify}
                disabled={loading}
                className="rounded-none bg-[#141414] text-[#E4E3E0] text-[10px] uppercase tracking-widest h-12"
              >
                {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : "Quantify Impact"}
              </Button>
              <Button 
                onClick={() => setIsManualDialogOpen(true)}
                variant="outline"
                className="rounded-none border-[#141414] text-[10px] uppercase tracking-widest h-12 hover:bg-[#141414] hover:text-[#E4E3E0]"
              >
                Manual PDF
              </Button>
            </div>
          </CardContent>
        </Card>

        <div className="space-y-6">
          {result ? (
            <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
              <Card className="border-[#141414] rounded-none shadow-none bg-[#141414] text-[#E4E3E0]">
                <CardHeader className="border-b border-[#E4E3E0]/20 py-4">
                  <CardTitle className="text-xs uppercase tracking-widest">Assessment Report</CardTitle>
                </CardHeader>
                <CardContent className="p-6 space-y-6">
                  <div className="flex justify-between items-end">
                    <div>
                      <p className="text-[10px] uppercase tracking-widest opacity-60">Estimated Total Loss</p>
                      <p className="text-5xl font-bold tracking-tighter">${result.estimatedLoss.toLocaleString()}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] uppercase tracking-widest opacity-60">Claim Eligibility</p>
                      <p className="text-xs font-bold text-green-400 uppercase">High Probability</p>
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-2 py-4 border-y border-[#E4E3E0]/10">
                    <div className="text-center">
                      <p className="text-[9px] uppercase opacity-60">Direct</p>
                      <p className="text-xs font-mono font-bold">${result.breakdown.directLoss.toLocaleString()}</p>
                    </div>
                    <div className="text-center border-x border-[#E4E3E0]/10">
                      <p className="text-[9px] uppercase opacity-60">Indirect</p>
                      <p className="text-xs font-mono font-bold">${result.breakdown.indirectLoss.toLocaleString()}</p>
                    </div>
                    <div className="text-center">
                      <p className="text-[9px] uppercase opacity-60">Reputation</p>
                      <p className="text-xs font-mono font-bold">${result.breakdown.reputationDamage.toLocaleString()}</p>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <p className="text-[10px] uppercase tracking-widest font-bold flex items-center gap-2">
                      <FileText className="w-3 h-3" /> Claim Justification
                    </p>
                    <p className="text-xs leading-relaxed italic opacity-80">
                      "{result.claimJustification}"
                    </p>
                  </div>

                  <Button 
                    onClick={handleGeneratePDF}
                    disabled={isGenerating}
                    className="w-full rounded-none bg-[#E4E3E0] text-[#141414] text-[10px] uppercase tracking-widest font-bold h-10 hover:bg-white"
                  >
                    {isGenerating ? (
                      <Loader2 className="w-4 h-4 animate-spin mr-2" />
                    ) : (
                      <Download className="w-4 h-4 mr-2" />
                    )}
                    {isGenerating ? "Generating PDF..." : "Generate Official Claim PDF"}
                  </Button>
                </CardContent>
              </Card>
            </motion.div>
          ) : (
            <div className="h-full border border-dashed border-[#141414] flex flex-col items-center justify-center gap-4 opacity-40 p-12 text-center">
              <FileText className="w-12 h-12" />
              <div>
                <p className="uppercase tracking-widest text-xs font-bold">No Assessment Generated</p>
                <p className="text-[10px] mt-2">Enter downtime details to calculate potential insurance payout.</p>
              </div>
            </div>
          )}
        </div>
      </div>

      <Card className="border-[#141414] rounded-none shadow-none bg-transparent">
        <CardHeader className="border-b border-[#141414] py-4 flex flex-row items-center justify-between space-y-0">
          <CardTitle className="text-xs uppercase tracking-widest">Recent Claims History</CardTitle>
          <Dialog open={isManualDialogOpen} onOpenChange={setIsManualDialogOpen}>
            <DialogTrigger 
              render={
                <Button variant="outline" size="sm" className="rounded-none border-[#141414] text-[9px] uppercase tracking-widest h-7 px-3 hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors font-bold" />
              }
            >
              <Plus className="w-3 h-3 mr-2" /> File Manual Claim
            </DialogTrigger>
            <DialogContent className="rounded-none border-[#141414] bg-[#E4E3E0] text-[#141414]">
              <DialogHeader>
                <DialogTitle className="text-sm uppercase tracking-widest font-bold">Manual Claim Submission</DialogTitle>
                <DialogDescription className="text-[10px] uppercase tracking-widest opacity-60">
                  Enter claim details to generate an official PDF report.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div className="space-y-2">
                  <Label className="text-[10px] uppercase tracking-widest font-bold">API Service Name</Label>
                  <Input 
                    placeholder="e.g. AWS Lambda" 
                    value={manualClaim.service}
                    onChange={(e) => setManualClaim({...manualClaim, service: e.target.value})}
                    className="rounded-none border-[#141414] bg-transparent font-mono"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-[10px] uppercase tracking-widest font-bold">Loss Amount (USD)</Label>
                  <Input 
                    type="number" 
                    placeholder="e.g. 5000" 
                    value={manualClaim.amount}
                    onChange={(e) => setManualClaim({...manualClaim, amount: e.target.value})}
                    className="rounded-none border-[#141414] bg-transparent font-mono"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-[10px] uppercase tracking-widest font-bold">Claim Justification</Label>
                  <textarea 
                    className="w-full min-h-[100px] p-3 rounded-none border border-[#141414] bg-transparent font-mono text-xs resize-none focus:outline-none"
                    placeholder="Provide technical justification for the claim..."
                    value={manualClaim.justification}
                    onChange={(e) => setManualClaim({...manualClaim, justification: e.target.value})}
                  />
                </div>
              </div>
              <DialogFooter>
                <Button 
                  onClick={handleManualSubmit}
                  className="w-full rounded-none bg-[#141414] text-[#E4E3E0] text-[10px] uppercase tracking-widest h-10"
                >
                  Generate Official PDF
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </CardHeader>
        <CardContent className="p-0">
          <table className="w-full text-left">
            <thead className="border-b border-[#141414] bg-[#D1D0CC]/50">
              <tr>
                <th className="p-3 text-[10px] uppercase tracking-widest font-bold">Claim ID</th>
                <th className="p-3 text-[10px] uppercase tracking-widest font-bold">API Service</th>
                <th className="p-3 text-[10px] uppercase tracking-widest font-bold">Date</th>
                <th className="p-3 text-[10px] uppercase tracking-widest font-bold">Amount</th>
                <th className="p-3 text-[10px] uppercase tracking-widest font-bold">Status</th>
                <th className="p-3 text-[10px] uppercase tracking-widest font-bold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#141414]">
              <tr key="claim-9921" className="text-xs font-mono">
                <td className="p-3">#CLM-9921</td>
                <td className="p-3 uppercase font-sans font-bold">Twilio SMS</td>
                <td className="p-3">2026-03-15</td>
                <td className="p-3">$12,450.00</td>
                <td className="p-3"><Badge className="bg-green-500 rounded-none text-[9px]">PAID</Badge></td>
                <td className="p-3 text-right">
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    className="h-8 w-8 p-0 rounded-none hover:bg-[#141414] hover:text-[#E4E3E0]"
                    onClick={() => handleGeneratePDF({ id: "CLM-9921", amount: 12450, timestamp: "2026-03-15", justification: "Official claim for Twilio SMS service interruption." })}
                  >
                    <Download className="w-3 h-3" />
                  </Button>
                </td>
              </tr>
              <tr key="claim-8842" className="text-xs font-mono opacity-60">
                <td className="p-3">#CLM-8842</td>
                <td className="p-3 uppercase font-sans font-bold">Stripe API</td>
                <td className="p-3">2026-02-01</td>
                <td className="p-3">$2,100.00</td>
                <td className="p-3"><Badge className="bg-green-500 rounded-none text-[9px]">PAID</Badge></td>
                <td className="p-3 text-right">
                  <Button 
                    variant="ghost" 
                    size="sm" 
                    className="h-8 w-8 p-0 rounded-none hover:bg-[#141414] hover:text-[#E4E3E0]"
                    onClick={() => handleGeneratePDF({ id: "CLM-8842", amount: 2100, timestamp: "2026-02-01", justification: "Official claim for Stripe API service interruption." })}
                  >
                    <Download className="w-3 h-3" />
                  </Button>
                </td>
              </tr>
            </tbody>
          </table>
        </CardContent>
      </Card>
    </div>
  );
}
